language: ruby

cache: bundler

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

gemfile:
  - gemfiles/haml4.gemfile
  - gemfiles/haml5.gemfile

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
