language: ruby

sudo: false

cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - rbx-2

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
