language: ruby

cache: bundler

rvm:
  - truffleruby-head

gemfile:
  - gemfiles/haml4.gemfile
  - gemfiles/haml5.0.gemfile
  - gemfiles/haml5.1.gemfile
  - gemfiles/haml5.2.gemfile

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
